HoaxSpreader/urls.py
from django.urls import path

from . import views

app_name = 'HoaxSpreader'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('skor/<int:cek>/', views.skor ),
    path('<int:id>/<int:cek>/', views.pertanyaan, name='pertanyaan' ),
    
]

TestHoax/urls.py
from django.urls import path

from . import views

app_name = 'TestHoax'

urlpatterns = [
    path('', views.testhoax, name='testhoax'),
    path('soal/', views.soal, name='soal'),
    path('soal2/<int:nomor>/<int:skor>', views.soal, name='soal2'),
    path('soal3/<int:nomor>/<int:skor>', views.soal, name='soal3'),
    path('soal4/<int:nomor>/<int:skor>', views.soal, name='soal4'),
    path('soal5/<int:nomor>/<int:skor>', views.soal, name='soal5'),
    path('skorhasil/<int:nomor>/<int:skor>', views.skor, name='skor'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.forum, name='forum1'),
    path('category/<str:category>/', views.forum, name='forum2'),
    path('addPost/', views.editPost, name='addPost'),
    path('editPost/<int:pk>/', views.editPost, name='editPost'),
    path('posts/<int:pk>/', views.readPost, name='readPost'),
    path('editComment/<int:pk>/', views.editComment, name='editComment'),
    path('addReply/<int:pkC>/', views.editReply, name='addReply'),
    path('editReply/<int:pkC>/<int:pkR>/', views.editReply, name='editReply'),
    path('addReplyReply//<int:pkR>/', views.editReply, name='addReplyReply'),
    path('profil/<str:username>/', views.profil, name='profil'),
    path('profil/<str:username>/warnaRandom/', views.warnaRandom, name='warnaRandom'),
    path('confirmDeletePost/<int:pk>/', views.confirmDeletePost, name='confirmDeletePost'),
    path('deletePost/<int:pk>/', views.deletePost, name='deletePost'),
    path('confirmDeleteComment/<int:pk>/', views.confirmDeleteComment, name='confirmDeleteComment'),
    path('deleteComment/<int:pk>/', views.deleteComment, name='deleteComment'),
    path('confirmDeleteReply/<int:pk>/', views.confirmDeleteReply, name='confirmDeleteReply'),
    path('deleteReply/<int:pk>/', views.deleteReply, name='deleteReply'),
]

hoax_destroyer/urls.py
from django.urls import path

from . import views

app_name = 'hoax_destroyer'

urlpatterns = [
    path('start/', views.start, name='start'),
    path('soal1/', views.soal1, name='soal1'),
    path('hasil1/<int:opsiid>/<int:nilaiid>/', views.hasil1, name='hasil1'),
    path('soal2/<int:nilaiid>/', views.soal2, name='soal2'),
    path('hasil2/<int:opsiid>/<int:nilaiid>/', views.hasil2, name='hasil2'),
    path('soal3/<int:nilaiid>/', views.soal3, name='soal3'),
    path('hasil3/<int:opsiid>/<int:nilaiid>/', views.hasil3, name='hasil3'),
    path('soal4/<int:nilaiid>/', views.soal4, name='soal4'),
    path('hasil4/<int:opsiid>/<int:nilaiid>/', views.hasil4, name='hasil4'),
    path('soal5/<int:nilaiid>/', views.soal5, name='soal5'),
    path('hasil5/<int:opsiid>/<int:nilaiid>/', views.hasil5, name='hasil5'),
    path('score/<int:nilaiid>/', views.score, name='score'),
    path('saranPertanyaan/', views.saranPertanyaan, name='saranPertanyaan'),
    path('saranPertanyaan/saveSaran', views.saveSaran),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

tk1ppwb12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('userAuth/', include('userAuth.urls')),
    path('userAuth/', include('django.contrib.auth.urls')),
    path('forum/', include('forum.urls')),
    path('HoaxSpreader/',include('HoaxSpreader.urls')),
    path('TestPengetahuan/',include('TestPengetahuan.urls')),
    path('hoax_destroyer/', include('hoax_destroyer.urls')),
    path('TestHoax/', include('TestHoax.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from forum.models import Color

def home(request):
    if request.user.is_authenticated:
        warnaUser = Color.objects.filter(user = request.user)
        if warnaUser:
            warnaUser = Color.objects.get(user = request.user)
    else:
        warnaUser = None
    return render(request, 'main/home.html', {'warnaUser' : warnaUser})
    
def about(request):
    if request.user.is_authenticated:
        warnaUser = Color.objects.filter(user = request.user)
        if warnaUser:
            warnaUser = Color.objects.get(user = request.user)
    else:
        warnaUser = None
    return render(request, 'main/about.html', {'warnaUser' : warnaUser})

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>FunCovidInfo | about</title>
<link rel="stylesheet" href="{% static 'main/css/style.css' %}" />
{% endblock meta %}

{% block content %}
    <div class="container" id="home">
        <div class="atasbawah">
            <div class="atasbawah" style="padding-bottom: 50px;">
                <div class="judul" style="padding-bottom: 20px;">
                    Tentang FunCovidInfo
                </div>
                <div class="about-background kanankiri">
                    <img src="{% static 'main/img/HoaxDestroyer.png' %}" class="paddingkanankiri" width=100px height=100px />
                    <div class="atasbawah alignatasbawahkiri paddingkanankiri">
                        <div class="judul-kecil">
                            Hoax Destroyer
                        </div>
                        <div class="isi">
                            Hoax Destroyer adalah salah satu mini games di <strong><span style="color: #80ffdb;">Fun</span><span style="color: #f28d8d;">Covid</span><span style="color: #e9ecf5;">Info</span></strong>. Akan diberikan soal dan pemain harus menjawab soal dengan jawaban yang akan menghancurkan hoax. Jika jawaban benar, pemain akan mendapatkan poin. Namun, jika pemain salah memberikan jawaban, maka pemain tidak akan mendapatkan poin. Skor akan diakumulasi di akhir permainan.
                        </div>
                    </div>
                </div>
                <div class="about-background kanankiri">
                    <div class="atasbawah alignatasbawahkanan paddingkanankiri">
                        <div class="judul-kecil">
                            Hoax Spreader
                        </div>
                        <div class="isi text-align-kanan">
                            Hoax Spreader adalah salah satu mini games di <strong><span style="color: #80ffdb;">Fun</span><span style="color: #f28d8d;">Covid</span><span style="color: #e9ecf5;">Info</span></strong>. Pada mini games ini akan diberikan sebuah narasi dan berbagai pilihan jawaban untuk para pemain. Pemain harus menjawab dengan jawaban yang akan menyebarkan hoax. Jika jawaban benar, pemain akan mendapatkan poin dan jika salah, pemain tidak akan mendapatkan poin. Skor akan diakumulasi di akhir permainan dan akan diberikan predikat.
                        </div>
                    </div>
                    <img src="{% static 'main/img/HoaxSpreader.png' %}" class="paddingkanankiri" width=100px height=100px />
                </div>
                <div class="about-background kanankiri">
                    <img src="{% static 'main/img/TestHoax.png' %}" class="paddingkanankiri" width=100px height=100px />
                    <div class="atasbawah alignatasbawahkiri paddingkanankiri">
                        <div class="judul-kecil">
                            Test Hoax
                        </div>
                        <div class="isi">
                            Test Hoax adalah salah satu tes pada <strong><span style="color: #80ffdb;">Fun</span><span style="color: #f28d8d;">Covid</span><span style="color: #e9ecf5;">Info</span></strong>. Pada test ini pemain akan diberikan berita/statement terkait Covid-19, lalu pemain harus menentukan apakah berita/statement tersebut termasuk hoax atau tidak. Jawaban dari test ini berupa pilihan benar/salah. Setelah menjawab, pemain akan mendapatkan tampilan jawaban yang benar dan pada akhir test pemain akan dapat melihat hasil keseluruhan dari test yang telah dikerjakan.
                        </div>
                    </div>
                </div>
                <div class="about-background kanankiri">
                    <div class="atasbawah alignatasbawahkanan paddingkanankiri">
                        <div class="judul-kecil">
                            Test Pengetahuan Covid-19
                        </div>
                        <div class="isi text-align-kanan">
                            Test Pengetahuan Covid-19 adalah salah satu tes pada <strong><span style="color: #80ffdb;">Fun</span><span style="color: #f28d8d;">Covid</span><span style="color: #e9ecf5;">Info</span></strong>. Test ini akan memuat soal pilihan ganda tentang pengetahuan umum seputar COVID-19. Jika pemain mendapatkan nilai akhir diatas 60 maka pemain akan diarahkan untuk pergi ke Forum. Sangat diharapkan pemain-pemain dapat membantu dalam menjawab pertanyaan di forum, jika nilai pemain kurang dari 60, pemain akan diminta untuk mengikuti tes dan mini games lain agar pemain dapat terus belajar dan mendapatkan pengetahuan.
                        </div>
                    </div>
                    <img src="{% static 'main/img/TestPengetahuanCovid-19.png' %}" class="paddingkanankiri" width=100px height=100px />
                </div>
                <div class="about-background kanankiri">
                    <img src="{% static 'main/img/DiskusiGeneral.png' %}" class="paddingkanankiri" width=100px height=100px />
                    <div class="atasbawah alignatasbawahkiri paddingkanankiri">
                        <div class="judul-kecil">
                            Forum
                        </div>
                        <div class="isi">
                            Forum adalah fasilitas tempat berdiskusi yang tersedia di <strong><span style="color: #80ffdb;">Fun</span><span style="color: #f28d8d;">Covid</span><span style="color: #e9ecf5;">Info</span></strong>. Forum Diskusi akan menjadi sarana komunikasi dan diskusi antar pengguna website. Selain sebagai tempat berbagi pengalaman dan pengetahuan, forum juga bisa menjadi tempat pengguna untuk beropini dan berdiskusi tentang berbagai informasi terkini Covid-19 dan juga masalah-masalah lain yang terjadi di dunia.
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="atasbawah" style="padding-bottom: 20px;">
                <div class="judul" style="padding-bottom: 20px;">
                    Tentang Kami
                </div>
                <div class="about-background">
                    <div class="subjudul">
                        Kelompok B12 PPW 2020/2021-1
                    </div>
                    <div class="anggota">
                        <p>Anggota:<br>
                        Athallah Rikza Ihsani (1906353523)<br>
                        Ferdi Fadillah (1906351083)<br>
                        Gerrad Natanael Daloma (1906398704)<br>
                        Michael Felix Haryono (1906398326)<br>
                        Rico Tadjudin (1906398364)<br></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>FunCovidInfo</title>
<link rel="stylesheet" href="{% static 'main/css/style.css' %}" />
{% endblock meta %}

{% block content %}
    <div class="container" id="home">
        <div class="atasbawah">
            <div class="judul" style="padding-bottom: 20px;">
                Selamat Datang di <br><span style="color: #80ffdb;">Fun</span><span style="color: #f28d8d;">Covid</span><span style="color: #e9ecf5;">Info</span>
            </div>
            <div class="kanankiri center" style="height: 120px;">
                <a href="{% url 'hoax_destroyer:start' %}" class="button1 bodyButton hd" style="font-size: 20px; width: 240px;">
                    <div class="kanankiri center" style="height: 50px;">
                        <img src="{% static 'main/img/HoaxDestroyer.png' %}" class="paddingkanan" width=40px height=40px />
                        Hoax Destroyer
                    </div>
                </a>
                <a href="{% url 'HoaxSpreader:home' %}" class="button1 bodyButton hs" style="font-size: 20px; width: 240px;">
                    <div class="kanankiri center" style="height: 50px;">
                        <img src="{% static 'main/img/HoaxSpreader.png' %}" class="paddingkanan" width=40px height=40px />
                        Hoax Spreader
                    </div>
                </a>
                <a href="{% url 'TestHoax:testhoax' %}" class="button1 bodyButton th" style="font-size: 20px; width: 240px;">
                    <div class="kanankiri center" style="height: 50px;">
                        <img src="{% static 'main/img/TestHoax.png' %}" class="paddingkanan" width=40px height=40px />
                        Test Hoax
                    </div>
                </a>
                <a href="{% url 'TestPengetahuan:home' %}" class="button1 bodyButton tp" style="font-size: 20px; width: 240px;">
                    <div class="kanankiri center" style="height: 50px;">
                        <img src="{% static 'main/img/TestPengetahuanCovid-19.png' %}" class="paddingkanan" width=40px height=40px />
                        Test Pengetahuan
                    </div>
                </a>
            </div>
            <div class="kanankiri center" style="height: 120px;">
                <a href="{% url 'forum:forum1' %}" class="button1 bodyButton" style="font-size: 20px; width: 150px;">
                    <div class="kanankiri center">
                        <img src="{% static 'main/img/DiskusiGeneral.png' %}" class="paddingkanan" width=40px height=40px />
                        Forum
                    </div>
                </a>
                <a href="{% url 'main:about' %}" class="button1 bodyButton" style="font-size: 20px; width: 150px;">
                    <div class="kanankiri center">
                        <img src="{% static 'main/img/DiskusiSaya.png' %}" class="paddingkanan" width=40px height=40px />
                        About
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock content %}